const SKILLS=['Wise Mind','Observe','Describe','Participate','Nonjudgmental','One-mindfully','Effectiveness','DEAR MAN','GIVE','FAST','Dialectics','Validation','Change Behavior','Observe Emotions','Check the Facts','Problem Solving','Opposite Action','Accumulate Positive','Build Mastery','Cope Ahead','PLEASE','Mindfulness Current Emotion','STOP','Pros/Cons','TIP','Distract'];
// A shared copy starts blank. Each person's private tracking areas are saved
// only in their own browser and are never included in these project files.
const DEFAULT_AREAS=[];
const KEY='steady-dbt-v1';
let state=load(); let interview=[]; let step=0; let draft={}; let selectedDate=localDate();
function load(){try{return JSON.parse(localStorage.getItem(KEY))||fresh()}catch{return fresh()}}
function fresh(){return{areas:DEFAULT_AREAS,therapistEmail:'',entries:{}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function localDate(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function parseDate(s){const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)}
function weekDates(base=parseDate(selectedDate)){const d=new Date(base),day=d.getDay(),offset=day===4?0:(day>4?day-4:day+3);const thu=new Date(d);thu.setDate(d.getDate()-offset);return Array.from({length:7},(_,i)=>{const x=new Date(thu);x.setDate(thu.getDate()+i);return x})}
function pretty(d,opt={weekday:'long',month:'long',day:'numeric'}){return d.toLocaleDateString(undefined,opt)}
function go(id){location.hash=id;document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));document.querySelectorAll('.topbar nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${id}`));if(id==='checkin')startInterview();if(id==='diary')renderDiary();if(id==='settings')renderSettings();window.scrollTo(0,0)}
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
window.addEventListener('hashchange',()=>go(location.hash.slice(1)||'home'));

function init(){const now=new Date();todayNumber.textContent=now.getDate();todayLabel.textContent=pretty(now,{weekday:'long',month:'long'});entryDate.max=localDate();entryDate.value=selectedDate;checkinDate.textContent=pretty(parseDate(selectedDate));entryDate.onchange=()=>{selectedDate=entryDate.value||localDate();checkinDate.textContent=pretty(parseDate(selectedDate));startInterview()};const done=state.entries[localDate()];if(done){statusRing.classList.add('done');statusRing.innerHTML='<span>Complete<br>✓</span>'}if(!state.areas.length){homePrimary.dataset.go='settings';homePrimary.innerHTML='Set up your diary card <span>→</span>'}else{gettingStarted.hidden=true}go(location.hash.slice(1)||'home')}
function startInterview(){entryDate.value=selectedDate;checkinDate.textContent=pretty(parseDate(selectedDate));const existing=state.entries[selectedDate]||{answers:{},skills:[],notes:''};draft=JSON.parse(JSON.stringify(existing));draft.answers ||= {};draft.skills ||= [];interview=[...state.areas.map(a=>({kind:'area',...a})),{kind:'skills',name:'DBT skills'},{kind:'notes',name:'A final note'}];step=0;renderQuestion()}
function renderQuestion(){const q=interview[step];progressText.textContent=`${step+1} of ${interview.length}`;progressBar.style.width=`${(step+1)/interview.length*100}%`;backQuestion.style.visibility=step?'visible':'hidden';nextQuestion.textContent=step===interview.length-1?'Finish check-in ✓':'Continue →';let html='';
  if(q.kind==='area'){const val=draft.answers[q.id]||{};html=`<div class="question-card"><p class="eyebrow">${q.type==='scale'?'Intensity · 0 to 5':q.type==='yesno'?'Today':'Reflection'}</p><h2>${questionFor(q)}</h2><p>${hintFor(q)}</p>${inputFor(q,val)}</div>`}
  if(q.kind==='skills')html=`<div class="question-card"><p class="eyebrow">Skills practice</p><h2>Which DBT skills did you use?</h2><p>Choose as many as you like—or none. Noticing attempts counts.</p><div class="skill-grid">${SKILLS.map(s=>`<label><input type="checkbox" name="skills" value="${s}" ${draft.skills.includes(s)?'checked':''}><span>${s}</span></label>`).join('')}</div></div>`;
  if(q.kind==='notes')html=`<div class="question-card"><p class="eyebrow">Closing reflection</p><h2>Anything else you want to remember?</h2><p>This is optional. A sentence or two is enough.</p><label>Notes<textarea id="notesInput" placeholder="What felt important today?">${escapeHtml(draft.notes||'')}</textarea></label></div>`;
  questionArea.innerHTML=html;
}
function questionFor(q){if(q.type==='scale')return `How strong was ${q.name.toLowerCase()} today?`;if(q.type==='text')return `What did you do well today?`;return `${q.name} today?`}
function hintFor(q){return q.type==='scale'?'0 means not present; 5 means as intense as it gets.':q.type==='text'?'Small wins and difficult things you survived both count.':'Choose yes or no, then add context if it would help.'}
function inputFor(q,val){if(q.type==='scale')return `<div class="scale">${[0,1,2,3,4,5].map(n=>`<label><input type="radio" name="answer" value="${n}" ${String(val.value)===String(n)?'checked':''}><span>${n}</span></label>`).join('')}</div><label>Optional note<input type="text" id="answerNote" value="${escapeAttr(val.note||'')}" placeholder="What was happening?"></label>`;if(q.type==='text')return `<label>Your answer<textarea id="textAnswer" placeholder="One thing I did well was…">${escapeHtml(val.value||'')}</textarea></label>`;return `<div class="choice-grid"><label><input type="radio" name="answer" value="Yes" ${val.value==='Yes'?'checked':''}><span>Yes</span></label><label><input type="radio" name="answer" value="No" ${val.value==='No'?'checked':''}><span>No</span></label></div><label>Optional note<input type="text" id="answerNote" value="${escapeAttr(val.note||'')}" placeholder="Add a little context"></label>`}
function capture(){const q=interview[step];if(q.kind==='area'){if(q.type==='text')draft.answers[q.id]={value:document.querySelector('#textAnswer')?.value.trim()||''};else draft.answers[q.id]={value:document.querySelector('input[name=answer]:checked')?.value||'',note:document.querySelector('#answerNote')?.value.trim()||''}}else if(q.kind==='skills')draft.skills=[...document.querySelectorAll('input[name=skills]:checked')].map(x=>x.value);else draft.notes=document.querySelector('#notesInput').value.trim()}
nextQuestion.onclick=()=>{capture();if(step<interview.length-1){step++;renderQuestion();scrollTo(0,0)}else{draft.completedAt=new Date().toISOString();state.entries[selectedDate]=draft;save();go('diary')}};
backQuestion.onclick=()=>{capture();if(step){step--;renderQuestion()}};

function renderSettings(){areaList.innerHTML=state.areas.map((a,i)=>`<div class="area-row"><label>Name<input data-field="name" data-i="${i}" value="${escapeAttr(a.name)}"></label><label>Answer style<select data-field="type" data-i="${i}"><option value="scale" ${a.type==='scale'?'selected':''}>Intensity 0–5</option><option value="yesno" ${a.type==='yesno'?'selected':''}>Yes / No + note</option><option value="text" ${a.type==='text'?'selected':''}>Written reflection</option></select></label><button type="button" class="remove-area" data-remove="${i}" aria-label="Remove ${escapeAttr(a.name)}">×</button></div>`).join('');therapistEmail.value=state.therapistEmail||'';document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.areas.splice(+b.dataset.remove,1);renderSettings()})}
addArea.onclick=()=>{state.areas.push({id:`area_${Date.now()}`,name:'New tracking area',type:'scale'});renderSettings()};
settingsForm.onsubmit=e=>{e.preventDefault();document.querySelectorAll('#areaList input,#areaList select').forEach(el=>state.areas[+el.dataset.i][el.dataset.field]=el.value.trim());state.areas=state.areas.filter(a=>a.name);state.therapistEmail=therapistEmail.value.trim();save();if(state.areas.length){gettingStarted.hidden=true;homePrimary.dataset.go='checkin';homePrimary.innerHTML='Begin today’s check-in <span>→</span>'}savedMessage.textContent='Saved';setTimeout(()=>savedMessage.textContent='',2000)};

function renderDiary(){const dates=weekDates(),range=`${pretty(dates[0],{month:'long',day:'numeric'})}–${pretty(dates[6],{month:'long',day:'numeric',year:'numeric'})}`;weekRange.textContent=range;documentTitle.textContent=`DBT Diary Card: ${range}`;trackingTable.innerHTML=`<thead><tr><th>Day</th>${state.areas.map(a=>`<th>${escapeHtml(a.name)}</th>`).join('')}</tr></thead><tbody>${dates.map(d=>{const e=state.entries[localDate(d)];return `<tr><td>${pretty(d,{weekday:'short',month:'numeric',day:'numeric'})}</td>${state.areas.map(a=>`<td>${formatAnswer(e?.answers?.[a.id])}</td>`).join('')}</tr>`}).join('')}</tbody>`;skillsTable.innerHTML=`<thead><tr><th>Skill</th>${dates.map(d=>`<th>${pretty(d,{weekday:'short'})}</th>`).join('')}</tr></thead><tbody>${SKILLS.map(s=>`<tr><td>${s}</td>${dates.map(d=>`<td>${state.entries[localDate(d)]?.skills?.includes(s)?'×':''}</td>`).join('')}</tr>`).join('')}</tbody>`}
function formatAnswer(a){if(!a)return '';const v=escapeHtml(String(a.value||'')),n=escapeHtml(a.note||'');return n?`${v}${v?' · ':''}${n}`:v}
printBtn.onclick=()=>window.print();
emailBtn.onclick=()=>{const dates=weekDates(),subject=encodeURIComponent(`DBT Diary Card — week of ${pretty(dates[0],{month:'short',day:'numeric'})}`),body=encodeURIComponent('Hi,\n\nI’d like to share my DBT diary card for this week. I’ll attach the PDF generated from Steady.\n\nThank you.');location.href=`mailto:${encodeURIComponent(state.therapistEmail||'')}?subject=${subject}&body=${body}`};
shareBtn.onclick=async()=>{const data={title:'DBT Diary Card',text:'My DBT diary card is ready. Use Print / Save PDF to create the complete two-table document.'};if(navigator.share)try{await navigator.share(data)}catch{}else alert('Sharing is not available in this browser. Use Print / Save PDF, then attach the PDF in your email or messaging app.')};
function escapeHtml(s){return String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}function escapeAttr(s){return escapeHtml(s).replace(/"/g,'&quot;')}
init();
